### ISSUE TITLE
Question, IPv6 visitor failure to send e-mail

### ISSUE THREAD

**Issue by slrslr** [xiaomlove/nexusphp#23] opened 2021-08-11 08:42 UTC
Hello,

i am using original Nexus script, not this reworked version and when i see IPv6 adrress in my profile /usercp.php
then the script fails to send out e-mail:
lang/langhere/lang_functions.php:	'**text_unable_to_send_mail**' => "...

it happens when IPv6 user try to submit personal message or new torrent

include/functions.php:		@mail($to, "=?".$hdr_encoding."?B?".base64_encode($subject)."?=", $body, "From: ".$SITEEMAIL.$eol."Content-type: text/html; charset=".$hdr_encoding.$eol, "-f$SITEEMAIL") or stderr($lang_functions['std_error'], $lang_functions['**text_unable_to_send_mail**']);

takeupload.php:if ($emailnotify_smtp=='yes' && $smtptype != 'none')
{
...
sent_mail($to,$SITENAME,$SITEEMAIL,change_email_encode(validlang($current_lang),$lang_takeupload_target[validlang($current_lang)]['mail_title'].$torrent),change_email_encode(validlang($current_lang),$body_arr[validlang($current_lang)]),"torrent upload",false,false,'',get_email_encode(validlang($current_lang)), "eYou");

anyone please having idea which particular code in which file may be causing this bug or where it was fixed in this repository?
I am using SMTP, external mail sending.

The error can be bypassed by commenting out
`or stderr($lang_functions['std_error'], $lang_functions['text_unable_to_send_mail'])`
in include/functions.php
but how to discover what is the actual error cause in case one is using IPv6?

**Comment by Oha-you** [comment] 2021-10-15 23:56
> i am using original Nexus script, not this reworked version

I'm not a maintainer, but I would close this issue after reading these lines :)
IMO, you shouldn't create issues for a codebase that you're not even using.

Setup a local environment and try to reproduce the same issue here. This repo is not a home for the original NexusPHP.
Also please format your code blocks with [Markdown](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code). Enable PHP highlighting as well (three backticks and `php`).

Also I found out that IPv6 support is working in this rewrite since [v1.6.0-beta5](https://nexusphp.org/2021/05/04/nexusphp-v1-6-0-beta5).

**Closed as completed** 2022-04-11 06:37 UTC
